# This example creates three ReplicatedJobs.
# Then node ReplicatedJob waits until the dataset-intializer and model-initializer ReplicatedJob are Complete.
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: multiple-depends-on
spec:
  replicatedJobs:
    - name: dataset-initializer
      template:
        spec:
          template:
            spec:
              containers:
                - name: initializer
                  image: busybox
                  command:
                    - /bin/sh
                    - -c
                    - "echo 'dataset-initializer runs for 10 seconds' && sleep 10"
    - name: model-initializer
      template:
        spec:
          template:
            spec:
              containers:
                - name: initializer
                  image: busybox
                  command:
                    - /bin/sh
                    - -c
                    - "echo 'model-initializer runs for 10 seconds' && sleep 10"
    - name: worker
      dependsOn:
        - name: dataset-initializer
          status: Complete
        - name: model-initializer
          status: Complete
      template:
        spec:
          parallelism: 4
          completions: 4
          template:
            spec:
              containers:
                - name: worker
                  image: busybox
                  command:
                    - /bin/sh
                    - -c
                    - "echo 'worker runs for 20 seconds' && sleep 20"
